# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insertar_asignatura.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from service import Asignatura_Service
from service import Curso_Service
from service import Anno_Service


class Ui_DialogInsertar(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(378, 137)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(30, 60, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(170, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setGeometry(QtCore.QRect(190, 60, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(40, 100, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 100, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(280, 60, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(290, 30, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_2.clicked.connect(self.on_pushButtonInsertar)
        self.cargar_combobox()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Insertar asignatura"))
        self.label.setText(_translate("Dialog", "Nombre Asignatura:"))
        self.label_2.setText(_translate("Dialog", "Horas de clase:"))
        self.pushButton.setText(_translate("Dialog", "Salir"))
        self.pushButton_2.setText(_translate("Dialog", "Insertar"))
        self.label_3.setText(_translate("Dialog", "Años:"))


    def on_pushButtonInsertar(self):
        cod_curso_actual = Curso_Service.Curso_Service.curso_actual(Curso_Service)[0][1]
        Asignatura_Service.Asignatura_Service.create_asignatura(Asignatura_Service, self.lineEdit.text(), self.spinBox.value(), Anno_Service.Anno_Service.get_cod_anno_por_curso(Anno_Service, int(self.comboBox.currentText()),cod_curso_actual ))
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("Asignatura insertada correctamente")
        msg.setWindowTitle("Información")
        msg.exec_()

    def cargar_combobox(self):
        curso_actual = Curso_Service.Curso_Service.curso_actual(Curso_Service)[0][0]
        annos = Anno_Service.Anno_Service.get_annos_x_curso(Anno_Service, curso_actual)
        for anno in annos:
            self.comboBox.addItem(str(anno.get_anno()))