# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modificar_asignatura.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from service import Asignatura_Service


class Ui_DialogModificar_Asignatura(object):
    def setupUi(self, Dialog, cod_asignatura):
        self.cod_asig = cod_asignatura
        Dialog.setObjectName("Dialog")
        Dialog.resize(290, 137)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(30, 60, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(170, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setGeometry(QtCore.QRect(190, 60, 42, 22))
        self.spinBox.setObjectName("spinBox")


        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(40, 100, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 100, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.on_pushButtonModificar)

        self.llenar_datos()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Modificar Asignatura"))
        self.label.setText(_translate("Dialog", "Nombre Asignatura:"))
        self.label_2.setText(_translate("Dialog", "Horas de clase:"))
        self.pushButton.setText(_translate("Dialog", "Salir"))
        self.pushButton_2.setText(_translate("Dialog", "Modificar"))

    def llenar_datos(self):
        datos = Asignatura_Service.Asignatura_Service.get_asignatura_por_codAsignatura(Asignatura_Service, self.cod_asig)
        self.lineEdit.setText(datos[0][0])
        self.spinBox.setValue(int(datos[0][1]))

    def on_pushButtonModificar(self):
        datos = Asignatura_Service.Asignatura_Service.get_asignatura_por_codAsignatura(Asignatura_Service, self.cod_asig)
        Asignatura_Service.Asignatura_Service.update_asignatura(Asignatura_Service, int(datos[0][3]),self.lineEdit.text(), self.spinBox.value(), int(datos[0][2]))
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("Asignatura modificada correctamente")
        msg.setWindowTitle("Información")
        msg.exec_()
