# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'promedios_por_grupo.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from service.Curso_Service import Curso_Service
from service.Anno_Service import Anno_Service
from service.Grupo_Service import Grupo_Service
from model.Anno import Anno
from model.Grupo import Grupo
from reports import Estudiantes_bajas



class Ui_DialogEstudiantes_bajas(object):
    def setupUi(self, Dialog):
        self.d = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(389, 264)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.comboBox_cursos = QtWidgets.QComboBox(Dialog)
        self.comboBox_cursos.setGeometry(QtCore.QRect(20, 70, 131, 22))
        self.comboBox_cursos.setObjectName("comboBox_cursos")
        self.comboBox_annos = QtWidgets.QComboBox(Dialog)
        self.comboBox_annos.setGeometry(QtCore.QRect(20, 150, 131, 22))
        self.comboBox_annos.setObjectName("comboBox_annos")
        self.labelCursos = QtWidgets.QLabel(Dialog)
        self.labelCursos.setGeometry(QtCore.QRect(60, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labelCursos.setFont(font)
        self.labelCursos.setObjectName("labelCursos")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 120, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 190, 47, 21))
        self.label_2.setObjectName("label_2")
        self.comboBox_grupos = QtWidgets.QComboBox(Dialog)
        self.comboBox_grupos.setGeometry(QtCore.QRect(20, 220, 131, 22))
        self.comboBox_grupos.setObjectName("comboBox_grupos")
        self.radioButton_anual = QtWidgets.QRadioButton(Dialog)
        self.radioButton_anual.setGeometry(QtCore.QRect(190, 70, 185, 23))
        self.radioButton_anual.setObjectName("radioButton_anual")
        self.radioButton_anual.setChecked(True)
        self.radioButton_acumulado = QtWidgets.QRadioButton(Dialog)
        self.radioButton_acumulado.setGeometry(QtCore.QRect(190, 130, 185, 23))
        self.radioButton_acumulado.setObjectName("radioButton_acumulado")
        self.Salir = QtWidgets.QPushButton(Dialog)
        self.Salir.setGeometry(QtCore.QRect(200, 220, 75, 23))
        self.Salir.setObjectName("Salir")
        self.pushButton_MostrarReporte = QtWidgets.QPushButton(Dialog)
        self.pushButton_MostrarReporte.setGeometry(QtCore.QRect(290, 220, 75, 23))
        self.pushButton_MostrarReporte.setObjectName("pushButton_MostrarReporte")
        self.radioButton_anual.clicked.connect(self.on_radioButton_anual)
        self.radioButton_acumulado.clicked.connect(self.on_radioButton_acumulado)
        self.pushButton_MostrarReporte.clicked.connect(self.on_pushButtonMostrarReporte)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.comboBox_cursos.activated.connect(self.cargar_comboBox_Annos)
        self.comboBox_annos.activated.connect(self.cargar_comboBox_grupos)
        self.cargar_comboBox_cursos()
        self.Salir.clicked.connect(self.d.close)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Escalafón"))
        self.labelCursos.setText(_translate("Dialog", "Curso"))
        self.label.setText(_translate("Dialog", "Año"))
        self.label_2.setText(_translate("Dialog", "Grupo"))
        self.radioButton_anual.setText(_translate("Dialog", "Bajas por grupo"))
        self.radioButton_acumulado.setText(_translate("Dialog", "Bajas por año"))
        self.Salir.setText(_translate("Dialog", "Salir"))
        self.pushButton_MostrarReporte.setText(_translate("Dialog", "Mostrar"))


    def cargar_comboBox_cursos(self):
        cursos = Curso_Service.read_curso(Curso_Service)
        for curso in cursos:
            self.comboBox_cursos.addItem(curso.get_curso())
        self.cargar_comboBox_Annos()

    def cargar_comboBox_Annos(self):
        self.comboBox_annos.clear()
        curso_selecionado = self.comboBox_cursos.currentText()
        annos = Anno_Service.get_annos_x_curso(Anno_Service, curso_selecionado)
        for anno in annos:
            self.comboBox_annos.addItem(str(anno.get_anno()))
        self.cargar_comboBox_grupos()

    def cargar_comboBox_grupos(self):
        self.comboBox_grupos.clear()
        anno_selecionado = self.comboBox_annos.currentText()
        curso_selecionado = self.comboBox_cursos.currentText()
        grupos = Grupo_Service.get_grupos_por_anno_y_curso(Grupo_Service, curso_selecionado,int(anno_selecionado))
        for grupo in grupos:
            self.comboBox_grupos.addItem(str(grupo[0]))

    def on_pushButtonMostrarReporte(self):
        if(self.radioButton_acumulado.isChecked()):
           Estudiantes_bajas.report_bajas_por_anno(self.comboBox_cursos.currentText(),
                                                 int(self.comboBox_annos.currentText()))
        else:
            Estudiantes_bajas.report_bajas_por_grupo(self.comboBox_cursos.currentText(),
                                                 int(self.comboBox_annos.currentText()),
                                                 int(self.comboBox_grupos.currentText()))


    def on_radioButton_anual(self):
        self.comboBox_grupos.setDisabled(False)

    def on_radioButton_acumulado(self):

        self.comboBox_grupos.setDisabled(True)