# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'repitentes_por_anno.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from service.Curso_Service import Curso_Service
from service.Anno_Service import Anno_Service
from model.Anno import Anno
from reports import Repitentes_por_anno


class Ui_Dialog_Repitentes(object):
    def setupUi(self, Dialog):
        self.d = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(237, 236)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.comboBox_cursos = QtWidgets.QComboBox(Dialog)
        self.comboBox_cursos.setGeometry(QtCore.QRect(50, 70, 131, 22))
        self.comboBox_cursos.setObjectName("comboBox_cursos")
        self.comboBox_annos = QtWidgets.QComboBox(Dialog)
        self.comboBox_annos.setGeometry(QtCore.QRect(50, 150, 131, 22))
        self.comboBox_annos.setObjectName("comboBox_annos")
        self.labelCursos = QtWidgets.QLabel(Dialog)
        self.labelCursos.setGeometry(QtCore.QRect(100, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labelCursos.setFont(font)
        self.labelCursos.setObjectName("labelCursos")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 120, 47, 13))
        self.label.setObjectName("label")
        self.Salir = QtWidgets.QPushButton(Dialog)
        self.Salir.setGeometry(QtCore.QRect(20, 200, 75, 23))
        self.Salir.setObjectName("Salir")
        self.pushButton_MostrarReporte = QtWidgets.QPushButton(Dialog)
        self.pushButton_MostrarReporte.setGeometry(QtCore.QRect(130, 200, 75, 23))
        self.pushButton_MostrarReporte.setObjectName("pushButton_MostrarReporte")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.pushButton_MostrarReporte.clicked.connect(self.on_pushButton_MostrarReporte)
        self.comboBox_cursos.activated.connect(self.cargar_comboBox_Annos)
        self.comboBox_annos.activated.connect(self.cargar_comboBox_cursos)
        self.cargar_comboBox_cursos()
        self.Salir.clicked.connect(self.d.close)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Repitentes por año"))
        self.labelCursos.setText(_translate("Dialog", "Curso"))
        self.label.setText(_translate("Dialog", "Año"))
        self.Salir.setText(_translate("Dialog", "Salir"))
        self.pushButton_MostrarReporte.setText(_translate("Dialog", "Mostrar"))


    def cargar_comboBox_cursos(self):
        cursos = Curso_Service.read_curso(Curso_Service)
        for curso in cursos:
            self.comboBox_cursos.addItem(curso.get_curso())
        self.cargar_comboBox_Annos()

    def cargar_comboBox_Annos(self):
        self.comboBox_annos.clear()
        curso_selecionado = self.comboBox_cursos.currentText()
        annos = Anno_Service.get_annos_x_curso(Anno_Service, curso_selecionado)
        for anno in annos:
            self.comboBox_annos.addItem(str(anno.get_anno()))

    def on_pushButton_MostrarReporte(self):
       Repitentes_por_anno.repitentes_por_anno(self.comboBox_cursos.currentText(),
                                                 int(self.comboBox_annos.currentText()))